export class TextKeys {
    public static addIssue = 'Add Issue';
    public static updateIssue = 'Update Issue';
    public static deleteIssue = 'Delete Issue';
    public static create = 'Create';
    public static update = 'Update';
    public static delete = 'Delete';
    public static userStory = 'User Story';
    public static bug = 'Bug';
    public static task = 'Task';
    public static spike = 'Spike';
    public static backlog = 'Backlog';
    public static plan = 'Plan';
    public static develop = 'Develop';
    public static test = 'Test';
    public static deploy = 'Deploy';
    public static done = 'Done';
    public static backlogColor = 'lightblue';
    public static planColor = '#e5da57';
    public static developColor = 'lightpink';
    public static testColor = '#a4bcc8';
    public static deployColor = '#76b0d9';
    public static doneColor = 'lightgreen';
    public static deleteConfirmationMessage = 'Are you sure, you want to delete Issue??';
    public static addMessage = 'Issue added successfully';
    public static updateMessage = 'Issue updated successfully';
    public static deleteMessage = 'Issue deleted successfully';
    public static errorMessage = 'There is some error. Please try again!!!';
}
